# ~/.config/starship.toml


# 输出后换行
add_newline = true


# 电池图标
[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "


# 当电量在 0% 到 10% 时以 "bold red" 样式显示
[[battery.display]]
threshold = 30
style = "bold red"


# 当电量在 10% 到 30% 时以 "bold yellow" 样式显示
[[battery.display]]
threshold = 60
style = "bold yellow"


# 当电量在 10% 到 30% 时以 "bold blue" 样式显示
[[battery.display]]
threshold = 100
style = "bold blue"


# 显示时间
[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "+8"
time_range = "10:00:00-14:00:00"


# 后台任务
[jobs]
symbol = "+ "
threshold = 4


# Git 分支图标
[git_branch]
symbol = "🔱 "
